const ISSUES = "https://github.com/mattiasutancykeln/gems/issues";
const CATEGORY_TITLES = [
  ["impl-decision", "Implementation decisions"],
  ["skill-prompt-tool", "Skills, prompts, tools"],
  ["pattern", "Patterns worth porting"],
  ["weak-spot", "Open threads / weak spots"],
  ["highlight", "Highlights"],
];

export function slugify(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40).replace(/-+$/, "");
}

export function gemPageName(gem) {
  return `${String(gem.number).padStart(4, "0")}-${slugify(gem.title)}.md`;
}

export function renderGemPage(gem, findings, allFindings) {
  const lines = [
    `# ${gem.title}`,
    "",
    "| | |",
    "|---|---|",
    `| Source | ${gem.url ?? "-"} |`,
    ...(gem.repo ? [`| Repo | https://github.com/${gem.repo}${gem.sha ? ` @ \`${gem.sha}\`` : ""} |`] : []),
    `| Kind | ${gem.source ?? "-"} |`,
    `| Topics | ${gem.topics.join(", ") || "-"} |`,
    `| License | ${gem.license ?? "none"} (${gem.codeReuse}) |`,
    `| Verdict | ${gem.verdict ?? "-"} |`,
    `| Findings | ${findings.length} |`,
    `| Issue | ${ISSUES}/${gem.number} |`,
    "",
  ];
  for (const [cat, catTitle] of CATEGORY_TITLES) {
    const catFindings = findings.filter((f) => f.category === cat);
    if (!catFindings.length) continue;
    lines.push(`## ${catTitle}`, "");
    for (const f of catFindings) {
      const cite = f.citation ? ` \`${f.citation}\`${f.sha ? ` @ ${f.sha}` : ""}` : "";
      lines.push(`<a id="${f.id}"></a>`, `### ${f.title}`, "", cite ? cite.trim() : "", "", f.text, "");
      const siblings = allFindings.filter((x) => x.clusterId === f.clusterId && x.gem !== f.gem);
      if (siblings.length) {
        const links = [...new Map(siblings.map((s) => [s.gem, s])).values()]
          .map((s) => `[gem #${s.gem}](${gemPageName({ number: s.gem, title: guessTitle(s, allFindings) })}#${s.id})`);
        lines.push(`Other takes: ${links.join(", ")}`, "");
      }
    }
  }
  return lines.filter((l, i, a) => l !== "" || a[i - 1] !== "").join("\n") + "\n";
}

// gem page links need the sibling gem's title; pages are rendered with the gems array available,
// so sync passes gems into renderCatalog/renderGemPage — helper resolves from a gems map set below.
let GEM_TITLES = new Map();
export function setGemTitles(gems) { GEM_TITLES = new Map(gems.map((g) => [g.number, g.title])); }
function guessTitle(finding, _all) { return GEM_TITLES.get(finding.gem) ?? `gem-${finding.gem}`; }

export function renderCatalog(gems, findings) {
  setGemTitles(gems);
  const clusters = new Map();
  for (const f of findings) {
    if (!clusters.has(f.clusterId)) clusters.set(f.clusterId, []);
    clusters.get(f.clusterId).push(f);
  }
  const multi = [...clusters.values()].filter((ms) => new Set(ms.map((m) => m.gem)).size >= 2)
    .sort((a, b) => (a.some((m) => m.quality === "high") ? 0 : 1) - (b.some((m) => m.quality === "high") ? 0 : 1) || b.length - a.length)
    .slice(0, 8);
  const lines = ["# Catalog", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", ""];
  if (multi.length) {
    lines.push("## Highlights", "", "Patterns with multiple independent implementations across gems:", "");
    for (const ms of multi) {
      const gemsIn = [...new Set(ms.map((m) => m.gem))].sort((a, b) => a - b);
      lines.push(`- ${ms.length} takes on "${ms[0].clusterLabel}" - ${gemsIn.map((g) => `[#${g}](${ISSUES}/${g})`).join(", ")}`);
    }
    lines.push("");
  }
  lines.push("## All gems", "", "| # | gem | source | topics | findings | license | verdict |", "|---|---|---|---|---|---|---|");
  const sorted = [...gems].sort((a, b) =>
    (a.quality === "high" ? 0 : 1) - (b.quality === "high" ? 0 : 1) || a.number - b.number);
  for (const g of sorted) {
    lines.push(`| [#${g.number}](${ISSUES}/${g.number}) | [${g.title}](gems/${gemPageName(g)}) | ${g.source ?? "-"} | ${g.topics.join(", ") || "-"} | ${g.findingCount} | ${g.license ?? "none"} (${g.codeReuse}) | ${g.verdict ?? "-"} |`);
  }
  return lines.join("\n") + "\n";
}

export function injectStats(readme, { gems, findings, clusters }) {
  const stats = `**${gems} gems · ${findings} findings · ${clusters} clusters** - MIT licensed`;
  return readme.replace(/<!-- stats:start -->[\s\S]*?<!-- stats:end -->/, `<!-- stats:start -->${stats}<!-- stats:end -->`);
}
