const ISSUES = "https://github.com/mattiasutancykeln/gems/issues";
const CATEGORY_TITLES = [
  ["impl-decision", "Implementation decisions"],
  ["skill-prompt-tool", "Skills, prompts, tools"],
  ["pattern", "Patterns worth porting"],
  ["weak-spot", "Open threads / weak spots"],
  ["highlight", "Highlights"],
];

export function slugify(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40).replace(/-+$/, "");
}

export function gemPageName(gem) {
  return `${String(gem.number).padStart(4, "0")}-${slugify(gem.title)}.md`;
}

export function renderGemPage(gem, findings, allFindings) {
  const lines = [
    `# ${gem.title}`,
    "",
    "| | |",
    "|---|---|",
    `| Source | ${gem.url ?? "-"} |`,
    ...(gem.repo ? [`| Repo | https://github.com/${gem.repo}${gem.sha ? ` @ \`${gem.sha}\`` : ""} |`] : []),
    `| Kind | ${gem.source ?? "-"} |`,
    `| Topics | ${gem.topics.join(", ") || "-"} |`,
    `| License | ${gem.license ?? "none"} (${gem.codeReuse}) |`,
    `| Verdict | ${gem.verdict ?? "-"} |`,
    `| Findings | ${findings.length} |`,
    `| Issue | ${ISSUES}/${gem.number} |`,
    "",
  ];
  for (const [cat, catTitle] of CATEGORY_TITLES) {
    const catFindings = findings.filter((f) => f.category === cat);
    if (!catFindings.length) continue;
    lines.push(`## ${catTitle}`, "");
    for (const f of catFindings) {
      const cite = f.citation ? ` \`${f.citation}\`${f.sha ? ` @ ${f.sha}` : ""}` : "";
      lines.push(`<a id="${f.id}"></a>`, `### ${f.title}`, "", cite ? cite.trim() : "", "", f.text, "");
      const siblings = allFindings.filter((x) => x.clusterId === f.clusterId && x.gem !== f.gem);
      if (siblings.length) {
        const links = [...new Map(siblings.map((s) => [s.gem, s])).values()]
          .map((s) => `[gem #${s.gem}](${gemPageName({ number: s.gem, title: guessTitle(s, allFindings) })}#${s.id})`);
        lines.push(`Other takes: ${links.join(", ")}`, "");
      }
    }
  }
  return lines.filter((l, i, a) => l !== "" || a[i - 1] !== "").join("\n") + "\n";
}

// gem page links need the sibling gem's title; pages are rendered with the gems array available,
// so sync passes gems into renderCatalog/renderGemPage — helper resolves from a gems map set below.
let GEM_TITLES = new Map();
export function setGemTitles(gems) { GEM_TITLES = new Map(gems.map((g) => [g.number, g.title])); }
function guessTitle(finding, _all) { return GEM_TITLES.get(finding.gem) ?? `gem-${finding.gem}`; }

export function renderCatalog(gems, findings) {
  setGemTitles(gems);
  const clusters = new Map();
  for (const f of findings) {
    if (!clusters.has(f.clusterId)) clusters.set(f.clusterId, []);
    clusters.get(f.clusterId).push(f);
  }
  const multi = [...clusters.values()].filter((ms) => new Set(ms.map((m) => m.gem)).size >= 2)
    .sort((a, b) => (a.some((m) => m.quality === "high") ? 0 : 1) - (b.some((m) => m.quality === "high") ? 0 : 1) || b.length - a.length)
    .slice(0, 8);
  const lines = ["# Catalog", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    "See also: [faceted index](corpus/INDEX.md) - browse by topic, source, category, or cluster.", ""];
  if (multi.length) {
    lines.push("## Highlights", "", "Patterns with multiple independent implementations across gems:", "");
    for (const ms of multi) {
      const gemsIn = [...new Set(ms.map((m) => m.gem))].sort((a, b) => a - b);
      lines.push(`- ${ms.length} takes on "${ms[0].clusterLabel}" - ${gemsIn.map((g) => `[#${g}](${ISSUES}/${g})`).join(", ")}`);
    }
    lines.push("");
  }
  lines.push("## All gems", "", "| # | gem | source | topics | findings | license | verdict |", "|---|---|---|---|---|---|---|");
  const sorted = [...gems].sort((a, b) =>
    (a.quality === "high" ? 0 : 1) - (b.quality === "high" ? 0 : 1) || a.number - b.number);
  for (const g of sorted) {
    lines.push(`| [#${g.number}](${ISSUES}/${g.number}) | [${g.title}](gems/${gemPageName(g)}) | ${g.source ?? "-"} | ${g.topics.join(", ") || "-"} | ${g.findingCount} | ${g.license ?? "none"} (${g.codeReuse}) | ${g.verdict ?? "-"} |`);
  }
  return lines.join("\n") + "\n";
}

function findingLine(f, gemsByNumber, prefix = "gems/") {
  const gemForId = gemsByNumber.get(f.gem) ?? { number: f.gem, title: GEM_TITLES.get(f.gem) ?? `gem-${f.gem}` };
  const cite = f.citation ? f.citation : "(no citation)";
  return `- [${f.title}](${prefix}${gemPageName(gemForId)}#${f.id}) — gem #${f.gem} · ${f.category} · \`${cite}\``;
}

// findings referenced from a shard file (one directory deeper than corpus/) need an extra ../
function shardFindingLine(f, gemsByNumber) {
  return findingLine(f, gemsByNumber, "../gems/");
}

function byGemThenId(a, b) {
  return a.gem - b.gem || String(a.id).localeCompare(String(b.id));
}

// filesystem-safe shard slug for a source repo, e.g. "acme/widget" -> "acme-widget"
function repoSlug(repo) {
  return repo.replace(/\//g, "-").replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
}

const SHARD_NOTE = "Findings are sharded to stay under the GitHub markdown render ceiling (see `oversizedPages`).";

export function renderIndexPages(gems, findings) {
  setGemTitles(gems);
  const gemsByNumber = new Map(gems.map((g) => [g.number, g]));
  const clusterCount = new Set(findings.map((f) => f.clusterId)).size;

  const pages = {};

  // by-topic.md (hub) + by-topic/<topic>.md (shards)
  // Grouped by shard FILENAME (slugify output), not the raw label: labels differing only in
  // case (e.g. "Agent" vs "agent") slugify to the same file and must merge into one shard
  // instead of the later group silently overwriting the earlier one in `pages`.
  const topicShards = new Map(); // slug -> { labels: Set<rawLabel>, findings: [] }
  const untagged = [];
  for (const f of findings) {
    if (!f.topic || !f.topic.length) { untagged.push(f); continue; }
    for (const t of f.topic) {
      const slug = slugify(t) || "topic";
      if (!topicShards.has(slug)) topicShards.set(slug, { labels: new Set(), findings: [] });
      const shard = topicShards.get(slug);
      shard.labels.add(t);
      shard.findings.push(f);
    }
  }
  const topicHubLines = ["# By topic", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    SHARD_NOTE, ""];
  const topicOrder = [...topicShards.entries()]
    .map(([slug, shard]) => ({ slug, shard, label: [...shard.labels].sort((a, b) => a.localeCompare(b))[0] }))
    .sort((a, b) => a.label.localeCompare(b.label));
  for (const { slug, shard, label } of topicOrder) {
    const group = [...shard.findings].sort(byGemThenId);
    topicHubLines.push(`- [${label}](by-topic/${slug}.md) (${group.length})`);
    const shardLines = [`# ${label}`, "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
      "[Back to by-topic index](../by-topic.md)", ""];
    for (const f of group) shardLines.push(shardFindingLine(f, gemsByNumber));
    pages[`by-topic/${slug}.md`] = shardLines.join("\n").replace(/\n+$/, "\n");
  }
  if (untagged.length) {
    const group = [...untagged].sort(byGemThenId);
    topicHubLines.push(`- [(untagged)](by-topic/untagged.md) (${group.length})`);
    const shardLines = ["# (untagged)", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
      "[Back to by-topic index](../by-topic.md)", ""];
    for (const f of group) shardLines.push(shardFindingLine(f, gemsByNumber));
    pages["by-topic/untagged.md"] = shardLines.join("\n").replace(/\n+$/, "\n");
  }
  topicHubLines.push("");
  pages["by-topic.md"] = topicHubLines.join("\n").replace(/\n+$/, "\n");

  // by-source.md (hub) + by-source/<repo-slug>.md (shards)
  // Grouped by shard FILENAME (repoSlug output), not the raw repo string, for the same reason
  // as by-topic above: two repo names that repoSlug to the same file must merge, not overwrite.
  const sourceShards = new Map(); // slug -> { repos: Set<rawRepo>, findings: [] }
  const noRepo = [];
  for (const f of findings) {
    if (!f.repo) { noRepo.push(f); continue; }
    const slug = repoSlug(f.repo);
    if (!sourceShards.has(slug)) sourceShards.set(slug, { repos: new Set(), findings: [] });
    const shard = sourceShards.get(slug);
    shard.repos.add(f.repo);
    shard.findings.push(f);
  }
  const sourceHubLines = ["# By source repo", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    SHARD_NOTE, ""];
  const repoOrder = [...sourceShards.entries()]
    .map(([slug, shard]) => ({ slug, shard, repo: [...shard.repos].sort((a, b) => a.localeCompare(b))[0] }))
    .sort((a, b) => b.shard.findings.length - a.shard.findings.length || a.repo.localeCompare(b.repo));
  for (const { slug, shard, repo } of repoOrder) {
    const group = [...shard.findings].sort(byGemThenId);
    sourceHubLines.push(`- [${repo}](https://github.com/${repo}) (${group.length}) -> [findings](by-source/${slug}.md)`);
    const shardLines = [`# ${repo}`, "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
      `[Back to by-source index](../by-source.md) · https://github.com/${repo}`, ""];
    for (const f of group) shardLines.push(shardFindingLine(f, gemsByNumber));
    pages[`by-source/${slug}.md`] = shardLines.join("\n").replace(/\n+$/, "\n");
  }
  if (noRepo.length) {
    const group = [...noRepo].sort(byGemThenId);
    sourceHubLines.push(`- [(no repo)](by-source/no-repo.md) (${group.length})`);
    const shardLines = ["# (no repo)", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
      "[Back to by-source index](../by-source.md)", ""];
    for (const f of group) shardLines.push(shardFindingLine(f, gemsByNumber));
    pages["by-source/no-repo.md"] = shardLines.join("\n").replace(/\n+$/, "\n");
  }
  sourceHubLines.push("");
  pages["by-source.md"] = sourceHubLines.join("\n").replace(/\n+$/, "\n");

  // by-category.md (hub) + by-category/<category>.md (shards)
  const categoryHubLines = ["# By category", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    SHARD_NOTE, ""];
  for (const [cat, catTitle] of CATEGORY_TITLES) {
    const group = findings.filter((f) => f.category === cat).sort(byGemThenId);
    if (!group.length) continue;
    categoryHubLines.push(`- [${catTitle}](by-category/${cat}.md) (${group.length})`);
    const shardLines = [`# ${catTitle}`, "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
      "[Back to by-category index](../by-category.md)", ""];
    for (const f of group) shardLines.push(shardFindingLine(f, gemsByNumber));
    pages[`by-category/${cat}.md`] = shardLines.join("\n").replace(/\n+$/, "\n");
  }
  categoryHubLines.push("");
  pages["by-category.md"] = categoryHubLines.join("\n").replace(/\n+$/, "\n");

  // by-cluster.md (single file, deliberately not sharded - stays small)
  const clusters = new Map();
  for (const f of findings) {
    if (!clusters.has(f.clusterId)) clusters.set(f.clusterId, []);
    clusters.get(f.clusterId).push(f);
  }
  const multiMember = [...clusters.entries()]
    .filter(([, members]) => members.length >= 2)
    .sort(([aId, a], [bId, b]) => b.length - a.length || String(aId).localeCompare(String(bId)));
  const clusterLines = ["# Cross-gem clusters", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    `${multiMember.length} clusters have 2 or more members.`, ""];
  for (const [, members] of multiMember) {
    const group = [...members].sort(byGemThenId);
    const gemNums = [...new Set(group.map((f) => f.gem))].sort((a, b) => a - b);
    clusterLines.push(`## ${group[0].clusterLabel} (${group.length} findings across gems ${gemNums.map((n) => `#${n}`).join(", ")})`, "");
    for (const f of group) clusterLines.push(findingLine(f, gemsByNumber));
    clusterLines.push("");
  }
  pages["by-cluster.md"] = clusterLines.join("\n").replace(/\n+$/, "\n");

  // INDEX.md
  pages["INDEX.md"] = [
    "# Corpus index",
    "",
    "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.",
    "",
    `${gems.length} gems · ${findings.length} findings · ${clusterCount} clusters`,
    "",
    "- [Catalog](../CATALOG.md) - highlights and the full gem table",
    "- [By topic](by-topic.md)",
    "- [By source repo](by-source.md)",
    "- [By category](by-category.md)",
    "- [Cross-gem clusters](by-cluster.md)",
    "",
  ].join("\n");

  return pages;
}

export function injectStats(readme, { gems, findings, clusters }) {
  const stats = `**${gems} gems · ${findings} findings · ${clusters} clusters** - MIT licensed`;
  return readme.replace(/<!-- stats:start -->[\s\S]*?<!-- stats:end -->/, `<!-- stats:start -->${stats}<!-- stats:end -->`);
}

// Flags generated markdown pages approaching GitHub's ~512KB render ceiling so sync can warn
// before a monolithic index page silently stops rendering.
export function oversizedPages(pagesObj, capBytes = 450_000) {
  const flagged = [];
  for (const [path, content] of Object.entries(pagesObj)) {
    const bytes = Buffer.byteLength(content, "utf8");
    if (bytes > capBytes) flagged.push({ path, bytes });
  }
  return flagged;
}
