const ISSUES = "https://github.com/mattiasutancykeln/gems/issues";
const CATEGORY_TITLES = [
  ["impl-decision", "Implementation decisions"],
  ["skill-prompt-tool", "Skills, prompts, tools"],
  ["pattern", "Patterns worth porting"],
  ["weak-spot", "Open threads / weak spots"],
  ["highlight", "Highlights"],
];

export function slugify(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40).replace(/-+$/, "");
}

export function gemPageName(gem) {
  return `${String(gem.number).padStart(4, "0")}-${slugify(gem.title)}.md`;
}

export function renderGemPage(gem, findings, allFindings) {
  const lines = [
    `# ${gem.title}`,
    "",
    "| | |",
    "|---|---|",
    `| Source | ${gem.url ?? "-"} |`,
    ...(gem.repo ? [`| Repo | https://github.com/${gem.repo}${gem.sha ? ` @ \`${gem.sha}\`` : ""} |`] : []),
    `| Kind | ${gem.source ?? "-"} |`,
    `| Topics | ${gem.topics.join(", ") || "-"} |`,
    `| License | ${gem.license ?? "none"} (${gem.codeReuse}) |`,
    `| Verdict | ${gem.verdict ?? "-"} |`,
    `| Findings | ${findings.length} |`,
    `| Issue | ${ISSUES}/${gem.number} |`,
    "",
  ];
  for (const [cat, catTitle] of CATEGORY_TITLES) {
    const catFindings = findings.filter((f) => f.category === cat);
    if (!catFindings.length) continue;
    lines.push(`## ${catTitle}`, "");
    for (const f of catFindings) {
      const cite = f.citation ? ` \`${f.citation}\`${f.sha ? ` @ ${f.sha}` : ""}` : "";
      lines.push(`<a id="${f.id}"></a>`, `### ${f.title}`, "", cite ? cite.trim() : "", "", f.text, "");
      const siblings = allFindings.filter((x) => x.clusterId === f.clusterId && x.gem !== f.gem);
      if (siblings.length) {
        const links = [...new Map(siblings.map((s) => [s.gem, s])).values()]
          .map((s) => `[gem #${s.gem}](${gemPageName({ number: s.gem, title: guessTitle(s, allFindings) })}#${s.id})`);
        lines.push(`Other takes: ${links.join(", ")}`, "");
      }
    }
  }
  return lines.filter((l, i, a) => l !== "" || a[i - 1] !== "").join("\n") + "\n";
}

// gem page links need the sibling gem's title; pages are rendered with the gems array available,
// so sync passes gems into renderCatalog/renderGemPage — helper resolves from a gems map set below.
let GEM_TITLES = new Map();
export function setGemTitles(gems) { GEM_TITLES = new Map(gems.map((g) => [g.number, g.title])); }
function guessTitle(finding, _all) { return GEM_TITLES.get(finding.gem) ?? `gem-${finding.gem}`; }

export function renderCatalog(gems, findings) {
  setGemTitles(gems);
  const clusters = new Map();
  for (const f of findings) {
    if (!clusters.has(f.clusterId)) clusters.set(f.clusterId, []);
    clusters.get(f.clusterId).push(f);
  }
  const multi = [...clusters.values()].filter((ms) => new Set(ms.map((m) => m.gem)).size >= 2)
    .sort((a, b) => (a.some((m) => m.quality === "high") ? 0 : 1) - (b.some((m) => m.quality === "high") ? 0 : 1) || b.length - a.length)
    .slice(0, 8);
  const lines = ["# Catalog", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    "See also: [faceted index](corpus/INDEX.md) - browse by topic, source, category, or cluster.", ""];
  if (multi.length) {
    lines.push("## Highlights", "", "Patterns with multiple independent implementations across gems:", "");
    for (const ms of multi) {
      const gemsIn = [...new Set(ms.map((m) => m.gem))].sort((a, b) => a - b);
      lines.push(`- ${ms.length} takes on "${ms[0].clusterLabel}" - ${gemsIn.map((g) => `[#${g}](${ISSUES}/${g})`).join(", ")}`);
    }
    lines.push("");
  }
  lines.push("## All gems", "", "| # | gem | source | topics | findings | license | verdict |", "|---|---|---|---|---|---|---|");
  const sorted = [...gems].sort((a, b) =>
    (a.quality === "high" ? 0 : 1) - (b.quality === "high" ? 0 : 1) || a.number - b.number);
  for (const g of sorted) {
    lines.push(`| [#${g.number}](${ISSUES}/${g.number}) | [${g.title}](gems/${gemPageName(g)}) | ${g.source ?? "-"} | ${g.topics.join(", ") || "-"} | ${g.findingCount} | ${g.license ?? "none"} (${g.codeReuse}) | ${g.verdict ?? "-"} |`);
  }
  return lines.join("\n") + "\n";
}

function findingLine(f, gemsByNumber) {
  const gemForId = gemsByNumber.get(f.gem) ?? { number: f.gem, title: GEM_TITLES.get(f.gem) ?? `gem-${f.gem}` };
  const cite = f.citation ? f.citation : "(no citation)";
  return `- [${f.title}](gems/${gemPageName(gemForId)}#${f.id}) — gem #${f.gem} · ${f.category} · \`${cite}\``;
}

function byGemThenId(a, b) {
  return a.gem - b.gem || String(a.id).localeCompare(String(b.id));
}

export function renderIndexPages(gems, findings) {
  setGemTitles(gems);
  const gemsByNumber = new Map(gems.map((g) => [g.number, g]));
  const clusterCount = new Set(findings.map((f) => f.clusterId)).size;

  const pages = {};

  // by-topic.md
  const topics = new Map();
  const untagged = [];
  for (const f of findings) {
    if (!f.topic || !f.topic.length) { untagged.push(f); continue; }
    for (const t of f.topic) {
      if (!topics.has(t)) topics.set(t, []);
      topics.get(t).push(f);
    }
  }
  const topicLines = ["# By topic", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", ""];
  for (const t of [...topics.keys()].sort((a, b) => a.localeCompare(b))) {
    const group = [...topics.get(t)].sort(byGemThenId);
    topicLines.push(`## ${t} (${group.length})`, "");
    for (const f of group) topicLines.push(findingLine(f, gemsByNumber));
    topicLines.push("");
  }
  if (untagged.length) {
    const group = [...untagged].sort(byGemThenId);
    topicLines.push(`## (untagged) (${group.length})`, "");
    for (const f of group) topicLines.push(findingLine(f, gemsByNumber));
    topicLines.push("");
  }
  pages["by-topic.md"] = topicLines.join("\n").replace(/\n+$/, "\n");

  // by-source.md
  const byRepo = new Map();
  const noRepo = [];
  for (const f of findings) {
    if (!f.repo) { noRepo.push(f); continue; }
    if (!byRepo.has(f.repo)) byRepo.set(f.repo, []);
    byRepo.get(f.repo).push(f);
  }
  const sourceLines = ["# By source repo", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", ""];
  const repoOrder = [...byRepo.keys()].sort((a, b) =>
    byRepo.get(b).length - byRepo.get(a).length || a.localeCompare(b));
  for (const repo of repoOrder) {
    const group = [...byRepo.get(repo)].sort(byGemThenId);
    const gemNums = [...new Set(group.map((f) => f.gem))].sort((a, b) => a - b);
    const gemLinks = gemNums.map((n) => {
      const g = gemsByNumber.get(n) ?? { number: n, title: GEM_TITLES.get(n) ?? `gem-${n}` };
      return `[gem #${n}](gems/${gemPageName(g)})`;
    });
    sourceLines.push(`## ${repo} (${group.length})`, "", `https://github.com/${repo} - ${gemLinks.join(", ")}`, "");
    for (const f of group) sourceLines.push(findingLine(f, gemsByNumber));
    sourceLines.push("");
  }
  if (noRepo.length) {
    const group = [...noRepo].sort(byGemThenId);
    sourceLines.push(`## (no repo) (${group.length})`, "");
    for (const f of group) sourceLines.push(findingLine(f, gemsByNumber));
    sourceLines.push("");
  }
  pages["by-source.md"] = sourceLines.join("\n").replace(/\n+$/, "\n");

  // by-category.md
  const categoryLines = ["# By category", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", ""];
  for (const [cat, catTitle] of CATEGORY_TITLES) {
    const group = findings.filter((f) => f.category === cat).sort(byGemThenId);
    if (!group.length) continue;
    categoryLines.push(`## ${catTitle} (${group.length})`, "");
    for (const f of group) categoryLines.push(findingLine(f, gemsByNumber));
    categoryLines.push("");
  }
  pages["by-category.md"] = categoryLines.join("\n").replace(/\n+$/, "\n");

  // by-cluster.md
  const clusters = new Map();
  for (const f of findings) {
    if (!clusters.has(f.clusterId)) clusters.set(f.clusterId, []);
    clusters.get(f.clusterId).push(f);
  }
  const multiMember = [...clusters.entries()]
    .filter(([, members]) => members.length >= 2)
    .sort(([aId, a], [bId, b]) => b.length - a.length || String(aId).localeCompare(String(bId)));
  const clusterLines = ["# Cross-gem clusters", "", "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.", "",
    `${multiMember.length} clusters have 2 or more members.`, ""];
  for (const [, members] of multiMember) {
    const group = [...members].sort(byGemThenId);
    const gemNums = [...new Set(group.map((f) => f.gem))].sort((a, b) => a - b);
    clusterLines.push(`## ${group[0].clusterLabel} (${group.length} findings across gems ${gemNums.map((n) => `#${n}`).join(", ")})`, "");
    for (const f of group) clusterLines.push(findingLine(f, gemsByNumber));
    clusterLines.push("");
  }
  pages["by-cluster.md"] = clusterLines.join("\n").replace(/\n+$/, "\n");

  // INDEX.md
  pages["INDEX.md"] = [
    "# Corpus index",
    "",
    "Generated by `scripts/sync-corpus.mjs` - do not edit by hand.",
    "",
    `${gems.length} gems · ${findings.length} findings · ${clusterCount} clusters`,
    "",
    "- [Catalog](../CATALOG.md) - highlights and the full gem table",
    "- [By topic](by-topic.md)",
    "- [By source repo](by-source.md)",
    "- [By category](by-category.md)",
    "- [Cross-gem clusters](by-cluster.md)",
    "",
  ].join("\n");

  return pages;
}

export function injectStats(readme, { gems, findings, clusters }) {
  const stats = `**${gems} gems · ${findings} findings · ${clusters} clusters** - MIT licensed`;
  return readme.replace(/<!-- stats:start -->[\s\S]*?<!-- stats:end -->/, `<!-- stats:start -->${stats}<!-- stats:end -->`);
}
