import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseIssue } from "../lib/parse-report.mjs";
import { clusterFindings } from "../lib/cluster.mjs";
import { codeReuseFor } from "../lib/license-map.mjs";
import { renderGemPage, renderCatalog, gemPageName, setGemTitles, injectStats } from "../lib/pages.mjs";

const REPO = "mattiasutancykeln/gems";

export function syncCorpus({ fetchIssues, fetchLicense, rootDir, log = console.error }) {
  const corpusDir = join(rootDir, "corpus");
  const pagesDir = join(corpusDir, "gems");
  mkdirSync(pagesDir, { recursive: true });

  const cachePath = join(corpusDir, ".licenses.json");
  const licenseCache = existsSync(cachePath) ? JSON.parse(readFileSync(cachePath, "utf8")) : {};

  const issues = fetchIssues();
  const gems = [];
  let findings = [];
  const warnings = [];

  for (const issue of [...issues].sort((a, b) => a.number - b.number)) {
    const parsed = parseIssue(issue);
    warnings.push(...parsed.warnings);
    const repo = parsed.gem.repo;
    let license = "none";
    if (repo) {
      if (!(repo in licenseCache)) { licenseCache[repo] = fetchLicense(repo); log(`license ${repo}: ${licenseCache[repo]}`); }
      license = licenseCache[repo] || "none";
    }
    if (license === "NOASSERTION") license = "none";
    const codeReuse = codeReuseFor(license === "none" ? null : license);
    const gem = { ...parsed.gem, license, codeReuse, findingCount: parsed.findings.length };
    gems.push(gem);
    for (const f of parsed.findings) findings.push({ ...f, topic: gem.topics, license, codeReuse, quality: gem.quality });
  }

  findings = clusterFindings(findings);
  const clusterCount = new Set(findings.map((f) => f.clusterId)).size;

  // write corpus
  writeFileSync(join(corpusDir, "gems.json"), JSON.stringify(gems, null, 2) + "\n");
  writeFileSync(join(corpusDir, "findings.jsonl"), findings.map((f) => JSON.stringify(f)).join("\n") + "\n");
  writeFileSync(cachePath, JSON.stringify(Object.fromEntries(Object.entries(licenseCache).sort()), null, 2) + "\n");

  setGemTitles(gems);
  for (const stale of readdirSync(pagesDir)) rmSync(join(pagesDir, stale));
  for (const gem of gems)
    writeFileSync(join(pagesDir, gemPageName(gem)), renderGemPage(gem, findings.filter((f) => f.gem === gem.number), findings));
  writeFileSync(join(rootDir, "CATALOG.md"), renderCatalog(gems, findings));

  const warnPath = join(corpusDir, "PARSE_WARNINGS.md");
  if (warnings.length)
    writeFileSync(warnPath, "# Parse warnings\n\nGenerated by sync-corpus. Fix the source comment or the parser.\n\n" + warnings.map((w) => `- ${w}`).join("\n") + "\n");
  else if (existsSync(warnPath)) rmSync(warnPath);

  const readmePath = join(rootDir, "README.md");
  if (existsSync(readmePath))
    writeFileSync(readmePath, injectStats(readFileSync(readmePath, "utf8"), { gems: gems.length, findings: findings.length, clusters: clusterCount }));

  log(`sync: ${gems.length} gems · ${findings.length} findings · ${clusterCount} clusters · ${warnings.length} warnings`);
  return { gems, findings, warnings };
}

// ---- CLI (gh-backed) ----
const EXEC_OPTS = { maxBuffer: 64 * 1024 * 1024, encoding: "utf8" };

function ghFetchIssues() {
  const list = JSON.parse(execFileSync("gh",
    ["issue", "list", "--repo", REPO, "--state", "all", "--limit", "500", "--json", "number,title,body,labels,url"], EXEC_OPTS));
  return list.map((i) => {
    const comments = JSON.parse(execFileSync("gh",
      ["issue", "view", String(i.number), "--repo", REPO, "--json", "comments", "--jq", "[.comments[].body]"], EXEC_OPTS));
    return { number: i.number, title: i.title, body: i.body ?? "", url: i.url,
      labels: i.labels.map((l) => l.name), comments };
  });
}

function ghFetchLicense(repo) {
  try {
    return execFileSync("gh", ["api", `repos/${repo}/license`, "--jq", ".license.spdx_id"], EXEC_OPTS).trim() || "none";
  } catch { return "none"; }
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
  if (process.argv.includes("--dry-run")) {
    const issues = ghFetchIssues();
    console.error(`dry-run: ${issues.length} issues fetched, no files written`);
  } else {
    const { warnings } = syncCorpus({ fetchIssues: ghFetchIssues, fetchLicense: ghFetchLicense, rootDir });
    if (warnings.length) console.error(`NOTE: ${warnings.length} parse warnings -> corpus/PARSE_WARNINGS.md`);
  }
}
